# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "212e6bf57233f5c54f3fc6837a2b90ad"
name = "UCP Demo"
application_url = "https://universal-agent-gateway.vercel.app"
embedded = true
handle = "universal-agent-gateway"

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "orders/create", "app/uninstalled" ]
  compliance_topics = [ "customers/redact", "customers/data_request", "shop/redact" ]
  uri = "/webhooks"

[access_scopes]
scopes = "write_products,read_products,read_orders,write_orders,read_checkouts,write_checkouts"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://universal-agent-gateway.vercel.app/auth/callback"
]

[app_proxy]
url = "https://universal-agent-gateway.vercel.app/api/proxy"
subpath = "agent"
prefix = "apps"

[pos]
embedded = false
